mv xoite_arg.c xoico_arg.c
mv xoite_arg.h xoico_arg.h
mv xoite_args.c xoico_args.c
mv xoite_args.h xoico_args.h
mv xoite_body.c xoico_body.c
mv xoite_body.h xoico_body.h
mv xoite_builder.c xoico_builder.c
mv xoite_builder.cfg xoico_builder.cfg
mv xoite_builder.h xoico_builder.h
mv xoite.c xoico.c
mv xoite_compiler.c xoico_compiler.c
mv xoite_compiler.h xoico_compiler.h
mv xoite_design.txt xoico_design.txt
mv xoite_feature.c xoico_feature.c
mv xoite_feature.h xoico_feature.h
mv xoite_forward.c xoico_forward.c
mv xoite_forward.h xoico_forward.h
mv xoite_func.c xoico_func.c
mv xoite_func.h xoico_func.h
mv xoite_funcs.c xoico_funcs.c
mv xoite_funcs.h xoico_funcs.h
mv xoite_group.c xoico_group.c
mv xoite_group.h xoico_group.h
mv xoite.h xoico.h
mv xoite_name.c xoico_name.c
mv xoite_name.h xoico_name.h
mv xoite_nested_group.c xoico_nested_group.c
mv xoite_nested_group.h xoico_nested_group.h
mv xoite_plant_builder.cfg xoico_plant_builder.cfg
mv xoite_planted.c xoico_planted.c
mv xoite_planted.h xoico_planted.h
mv xoite_signature.c xoico_signature.c
mv xoite_signature.h xoico_signature.h
mv xoite_source.c xoico_source.c
mv xoite_source.h xoico_source.h
mv xoite_stamp.c xoico_stamp.c
mv xoite_stamp.h xoico_stamp.h
mv xoite_target.c xoico_target.c
mv xoite_target.h xoico_target.h
mv xoite_xoi_out.c xoico_xoi_out.c
mv xoite_xoi_out.h xoico_xoi_out.h
mv xoite_xoite_builder.cfg xoico_xoite_builder.cfg
